---
- name: "Browsers: geckodriver | Check if geckodriver is installed"
  become: true
  ansible.builtin.shell: geckodriver --version | head -n1 | cut -d" " -f2
  register: already_installed
  ignore_errors: true
  changed_when: already_installed.rc != 0

- name: "Browsers: geckodriver: Download"
  ansible.builtin.get_url:
    url: "{{ geckodriver_url }}"
    dest: /tmp
    checksum: sha512:{{ geckodriver_checksum }}
    mode: "0600"
  when: already_installed.stdout != geckodriver_version

- name: "Browsers: geckodriver: Uncompress"
  ansible.builtin.unarchive:
    src: /tmp/{{ geckodriver_file_name }}
    dest: /usr/local/bin/
    copy: false
  when: already_installed.stdout != geckodriver_version
