---

# Python 2.6
- name: "python (py26): add deadsnakes PPA"
  become: yes
  apt_repository:
    repo='ppa:fkrull/deadsnakes'

- name: "python (py26):: update"
  become: yes
  apt:
    upgrade=dist
    update_cache=yes

- name: "python (py26):: install python 2.6"
  become: yes
  apt:
    name={{ item }}
    state=present
  with_items:
    - python2.6
    - python2.6-dev

# pip on python 2.7 and 3.5
- name: "python (pip): download get-pip.py"
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: 0440

- name: "python (pip): install pip on py27"
  become: yes
  shell: python2.7 /tmp/get-pip.py
  args:
    creates: /usr/local/bin/pip2.7

- name: "python (pip): install pip on py35"
  become: yes
  shell: python3.5 /tmp/get-pip.py
  args:
    creates: /usr/local/bin/pip3.5

- name: "python (py27): install pygithub globally"
  become: yes
  shell: pip2.7 install pygithub==1.26.0

- name: "python (py35): install pygithub globally"
  become: yes
  shell: pip3.5 install pygithub==1.26.0

# Create a virtualenv with requests on it
- name: "python (venv): copy requirements.txt"
  become: yes
  become_user: jenkins
  copy:
    src=requirements.txt
    dest=/tmp/requirements.txt
    owner=jenkins
    group=jenkins

- name: "python (venv): create virtual environment"
  become: yes
  become_user: jenkins
  pip:
    requirements=/tmp/requirements.txt
    virtualenv=/home/jenkins/venv-requests
    virtualenv_command=/usr/bin/virtualenv
