---

- name: "Handlers: restart fail2ban"
  service:
    name=fail2ban
    state=restarted

- name: "Handlers: restart unattended-upgrades"
  service:
    name=unattended-upgrades
    state=restarted
